// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eazzbfxkbzzqyunkvkta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhenpiZnhrYnp6cXl1bmt2a3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTcyNTMsImV4cCI6MjA2NzYzMzI1M30.lcbggpdmovW1afPZmEk7zlQNi2IMgUWGQghHQDwWGiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});